name: why-think-step-by-step
channels:
  - ankurankan
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.6.1
  - antlr-python-runtime=4.9.3
  - arrow-cpp=9.0.0
  - async-timeout=4.0.2
  - attr=2.5.1
  - attrs=22.1.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - blessings=1.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.1.0
  - colorama=0.4.5
  - cryptography=37.0.4
  - cudatoolkit=11.7.0
  - cudnn=8.4.1.50
  - cycler=0.11.0
  - dataclasses=0.8
  - datasets=2.4.0
  - dbus=1.13.6
  - dill=0.3.5.1
  - expat=2.4.8
  - fftw=3.3.10
  - filelock=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.0
  - freetype=2.12.1
  - frozenlist=1.3.1
  - fsspec=2022.7.1
  - gettext=0.19.8.1
  - gflags=2.2.2
  - glib=2.72.1
  - glib-tools=2.72.1
  - glog=0.6.0
  - grpc-cpp=1.46.4
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - huggingface_hub=0.8.1
  - hydra-core=1.2.0
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.9.0
  - jack=1.9.18
  - joblib=1.1.0
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libabseil=20211102.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.64
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=7.83.1
  - libcxx=14.0.6
  - libcxxabi=14.0.6
  - libdb=6.2.32
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.3.4
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgoogle-cloud=1.40.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.5
  - libprotobuf=3.20.1
  - libsndfile=1.0.31
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libudev1=249
  - libutf8proc=2.7.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - magma=2.5.4
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2022.1.0
  - multidict=6.0.2
  - multiprocess=0.70.13
  - munkres=1.1.4
  - mysql-common=8.0.30
  - mysql-libs=8.0.30
  - nccl=2.14.3.1
  - ncurses=6.3
  - networkx=2.8.8
  - ninja=1.11.0
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.2
  - nvidia-ml=7.352.0
  - omegaconf=2.2.2
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - orc=1.7.5
  - packaging=21.3
  - pandas=1.4.3
  - parquet-cpp=1.5.1
  - pathlib=1.0.1
  - patsy=0.5.2
  - pcre=8.45
  - pgmpy=0.1.22
  - pillow=9.2.0
  - pip=22.2.2
  - ply=3.11
  - pomegranate=0.14.8
  - portaudio=19.6.0
  - psutil=5.9.1
  - pthread-stubs=0.4
  - pulseaudio=14.0
  - pyarrow=9.0.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyprojroot=0.2.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.10.5
  - python-dateutil=2.8.2
  - python-xxhash=3.0.0
  - python_abi=3.10
  - pytorch=1.12.1
  - pytz=2022.2.1
  - pyyaml=6.0
  - qt-main=5.15.4
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - s2n=1.0.10
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - seaborn=0.12.0
  - seaborn-base=0.12.0
  - setuptools=65.0.2
  - sip=6.6.2
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.9
  - sqlite=3.39.2
  - statsmodels=0.13.2
  - tbb=2021.5.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - tqdm=4.64.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wheel=0.37.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - evaluate==0.2.2
    - regex==2022.8.17
    - responses==0.18.0
    - tokenizers==0.12.1
    - transformers==4.21.1
